import MenuItem from "../types/MenuItem";

const veganMenu: MenuItem[] = [
  {
    id: "1",
    name: "Vegan Burger",
    description: "A delicious vegan patty with lettuce, tomato, and avocado.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/1.jpg",
    price: 64950,
    isBestSeller: true,
    amount: 100,
    isBooked: false,
  },
  {
    id: "2",
    name: "Vegan Tacos",
    description:
      "Soft tortillas filled with seasoned jackfruit and fresh vegetables.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/2.jpg",
    price: 49950,
    isBestSeller: true,
    amount: 50,
    isBooked: false,
  },
  {
    id: "3",
    name: "Vegan Chocolate Smoothie",
    description:
      "A creamy, chocolate-flavored smoothie with almond milk and banana.",
    category: "drink",
    image: "https://imghost.sirv.com/vegelunch/3.jpg",
    price: 19950,
    isBestSeller: false,
    amount: 200,
    isBooked: false,
  },
  {
    id: "4",
    name: "Chickpea Salad",
    description: "A fresh salad with chickpeas, cucumber, and tahini dressing.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/4.jpg",
    price: 26650,
    isBestSeller: false,
    amount: 60,
    isBooked: false,
  },
  {
    id: "5",
    name: "Vegan Nachos",
    description: "Corn chips topped with vegan cheese, guacamole, and salsa.",
    category: "snack",
    image: "https://imghost.sirv.com/vegelunch/5.jpg",
    price: 23300,
    isBestSeller: false,
    amount: 150,
    isBooked: false,
  },
  {
    id: "6",
    name: "Lemonade",
    description: "A refreshing homemade lemonade with a hint of mint.",
    category: "drink",
    image: "https://imghost.sirv.com/vegelunch/6.jpg",
    price: 13300,
    isBestSeller: false,
    amount: 300,
    isBooked: false,
  },
  {
    id: "7",
    name: "Vegan Pizza",
    description:
      "A gluten-free pizza topped with vegan cheese, mushrooms, and olives.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/7.jpg",
    price: 49950,
    isBestSeller: true,
    amount: 80,
    isBooked: false,
  },
  {
    id: "8",
    name: "Açaí Bowl",
    description:
      "A refreshing bowl of açaí topped with granola, banana, and berries.",
    category: "snack",
    image: "https://imghost.sirv.com/vegelunch/8.jpg",
    price: 29950,
    isBestSeller: false,
    amount: 120,
    isBooked: false,
  },
  {
    id: "9",
    name: "Coconut Water",
    description: "Natural coconut water served fresh and chilled.",
    category: "drink",
    image: "https://imghost.sirv.com/vegelunch/9.jpg",
    price: 14950,
    isBestSeller: false,
    amount: 250,
    isBooked: false,
  },
  {
    id: "10",
    name: "Vegan Wrap",
    description:
      "Whole wheat wrap filled with hummus, cucumber, and mixed greens.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/10.jpg",
    price: 31650,
    isBestSeller: false,
    amount: 130,
    isBooked: false,
  },
  {
    id: "11",
    name: "Vegan Muffin",
    description: "A soft and fluffy muffin made with oat flour and berries.",
    category: "snack",
    image: "https://imghost.sirv.com/vegelunch/11.jpg",
    price: 16650,
    isBestSeller: false,
    amount: 200,
    isBooked: false,
  },
  {
    id: "12",
    name: "Green Smoothie",
    description:
      "A nutritious smoothie made with kale, spinach, and green apple.",
    category: "drink",
    image: "https://imghost.sirv.com/vegelunch/12.jpg",
    price: 21650,
    isBestSeller: true,
    amount: 180,
    isBooked: false,
  },
  {
    id: "13",
    name: "Vegan Sushi",
    description:
      "Vegan sushi rolls made with avocado, cucumber, and pickled ginger.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/13.jpg",
    price: 43300,
    isBestSeller: false,
    amount: 70,
    isBooked: false,
  },
  {
    id: "14",
    name: "Oatmeal Cookies",
    description: "Crunchy and chewy oatmeal cookies with raisins and cinnamon.",
    category: "snack",
    image: "https://imghost.sirv.com/vegelunch/14.jpg",
    price: 13300,
    isBestSeller: false,
    amount: 220,
    isBooked: false,
  },
  {
    id: "15",
    name: "Hibiscus Tea",
    description: "A floral, refreshing tea made from hibiscus flowers.",
    category: "drink",
    image: "https://imghost.sirv.com/vegelunch/15.jpg",
    price: 13300,
    isBestSeller: true,
    amount: 150,
    isBooked: false,
  },
  {
    id: "16",
    name: "Falafel Plate",
    description: "Crispy falafel served with tahini sauce and a side of salad.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/16.jpg",
    price: 34950,
    isBestSeller: false,
    amount: 90,
    isBooked: false,
  },
  {
    id: "17",
    name: "Vegan Pancakes",
    description:
      "Fluffy vegan pancakes served with maple syrup and fresh berries.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/17.jpg",
    price: 39950,
    isBestSeller: true,
    amount: 110,
    isBooked: false,
  },
  {
    id: "18",
    name: "Vegan Burrito",
    description: "A large burrito filled with black beans, rice, and avocado.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/18.jpg",
    price: 31650,
    isBestSeller: false,
    amount: 80,
    isBooked: false,
  },
  {
    id: "19",
    name: "Mango Smoothie",
    description:
      "A tropical smoothie made with fresh mangoes and coconut milk.",
    category: "drink",
    image: "https://imghost.sirv.com/vegelunch/19.jpg",
    price: 18300,
    isBestSeller: true,
    amount: 220,
    isBooked: false,
  },
  {
    id: "20",
    name: "Vegan Mac and Cheese",
    description: "A creamy mac and cheese made with cashew cheese and pasta.",
    category: "food",
    image: "https://imghost.sirv.com/vegelunch/20.jpg",
    price: 44950,
    isBestSeller: true,
    amount: 90,
    isBooked: false,
  },
];

export default veganMenu;
